title: website
author:
  name: Gurtej Saini
  email: grrtej@gmail.com

theme: minima

minima:
  social_links:
    - { platform: github, user_url: "https://github.com/grrtej" }
    - { platform: instagram, user_url: "https://www.instagram.com/grrtej" }
    - { platform: linkedin, user_url: "https://www.linkedin.com/in/grrtej" }
    - { platform: twitter, user_url: "https://twitter.com/grrtej" }
    - { platform: youtube, user_url: "https://www.youtube.com/@grrtej" }
